export default [
  {
    id: 1,
    firstname: "Edan",
    lastname: "Covelle",
    gender: "Male",
    address: "800 Chinook Lane",
    city: "Mačkovec",
    country: "Croatia",
    phone: "2906956964",
    email: "ecovelle0@desdev.cn",
    avatar: "https://robohash.org/nequeiustosapiente.png?size=50x50&set=set1",
  },
  {
    id: 2,
    firstname: "Zach",
    lastname: "Jays",
    gender: "Male",
    address: "271 Logan Terrace",
    city: "Baoxing",
    country: "China",
    phone: "7638760782",
    email: "zjays1@dropbox.com",
    avatar:
      "https://robohash.org/necessitatibusquovitae.png?size=50x50&set=set1",
  },
  {
    id: 3,
    firstname: "August",
    lastname: "Rives",
    gender: "Male",
    address: "6 Sullivan Trail",
    city: "Olkusz",
    country: "Poland",
    phone: "1586746786",
    email: "arives2@freewebs.com",
    avatar:
      "https://robohash.org/reiciendisfacilisvoluptas.png?size=50x50&set=set1",
  },
  {
    id: 4,
    firstname: "Grete",
    lastname: "Siddons",
    gender: "Female",
    address: "64051 Kensington Hill",
    city: "Stari Kuty",
    country: "Ukraine",
    phone: "4673910869",
    email: "gsiddons3@studiopress.com",
    avatar: "https://robohash.org/numquamfugaquis.png?size=50x50&set=set1",
  },
  {
    id: 5,
    firstname: "Marna",
    lastname: "MacGeffen",
    gender: "Female",
    address: "9604 Beilfuss Way",
    city: "Ngurensiti",
    country: "Indonesia",
    phone: "6701743962",
    email: "mmacgeffen4@github.io",
    avatar: "https://robohash.org/reiciendiseaquein.png?size=50x50&set=set1",
  },
  {
    id: 6,
    firstname: "Karlene",
    lastname: "Laverenz",
    gender: "Female",
    address: "028 Buena Vista Alley",
    city: "Kotanopan",
    country: "Indonesia",
    phone: "9425910862",
    email: "klaverenz5@slideshare.net",
    avatar: "https://robohash.org/voluptascumplaceat.png?size=50x50&set=set1",
  },
  {
    id: 7,
    firstname: "Margalo",
    lastname: "Zapatero",
    gender: "Female",
    address: "31714 Hauk Terrace",
    city: "Huangbu",
    country: "China",
    phone: "2495314040",
    email: "mzapatero6@narod.ru",
    avatar: "https://robohash.org/placeatquaecum.png?size=50x50&set=set1",
  },
  {
    id: 8,
    firstname: "Blondelle",
    lastname: "Lloyd",
    gender: "Female",
    address: "35 Walton Avenue",
    city: "Lukou",
    country: "China",
    phone: "5067941877",
    email: "blloyd7@cbslocal.com",
    avatar: "https://robohash.org/enimducimusfugiat.png?size=50x50&set=set1",
  },
  {
    id: 9,
    firstname: "Jeramie",
    lastname: "Galliard",
    gender: "Male",
    address: "3515 Melby Terrace",
    city: "Kilim",
    country: "Philippines",
    phone: "7519903024",
    email: "jgalliard8@state.tx.us",
    avatar: "https://robohash.org/asperioresesseet.png?size=50x50&set=set1",
  },
  {
    id: 10,
    firstname: "Neysa",
    lastname: "Ridsdole",
    gender: "Female",
    address: "80623 Rowland Circle",
    city: "Naebugis",
    country: "Indonesia",
    phone: "8167330804",
    email: "nridsdole9@loc.gov",
    avatar: "https://robohash.org/namipsumrepellat.png?size=50x50&set=set1",
  },
];
